name=MenuLibrary
version=0.0.1
author=thirstyice
maintainer=thirstyice - https://github.com/thirstyice
sentence=An arduino menu library
paragraph=I wanted a menu library where the code was easy to read, easy to extend, and made sense.
	Most menu libraries I found to be hard to read for a beginner, so I made this library as an alternative.
category=Uncategorized
url=https://github.com/thirstyice/MenuLibrary
architectures=*
